name: obeypay
description: "App for people into Findom relations to meet, chat, and spend money."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.0.0
  flutter_svg: ^2.0.17
  scrumlab_flutter_tindercard: ^1.2.0
  flutter_card_swiper: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Playfair.ttf
    - assets/icons/certified.svg
    - assets/images/

  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/Playfair.ttf