import 'objects/user.dart';

final List<User> DemoUsers = [
  User(
    id: 1,
    name: "Methew Johnsons",
    email: "test@test.com",
    age: 25,
    isSub: true,
    isCertified: true,
    jobTitle: "Senior Programmer",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "200",
    totalSpent: "2k",
  ),
  User(
    id: 2,
    name: "Alice Brown",
    email: "alice@example.com",
    age: 30,
    isSub: false,
    isCertified: false,
    jobTitle: "Product Manager",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "500",
    totalSpent: "10k",
  ),
  User(
    id: 3,
    name: "John Doe",
    email: "john@example.com",
    age: 28,
    isSub: true,
    isCertified: true,
    jobTitle: "Software Engineer",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "300",
    totalSpent: "5k",
  ),
  User(
    id: 4,
    name: "Emma Watson",
    email: "emma@example.com",
    age: 26,
    isSub: false,
    isCertified: false,
    jobTitle: "UX Designer",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "400",
    totalSpent: "8k",
  ),
  User(
    id: 5,
    name: "David Miller",
    email: "david@example.com",
    age: 32,
    isSub: true,
    isCertified: true,
    jobTitle: "Data Scientist",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "600",
    totalSpent: "12k",
  ),
  User(
    id: 6,
    name: "Sophia Wilson",
    email: "sophia@example.com",
    age: 27,
    isSub: false,
    isCertified: true,
    jobTitle: "Marketing Specialist",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "350",
    totalSpent: "7k",
  ),
  User(
    id: 7,
    name: "James Anderson",
    email: "james@example.com",
    age: 29,
    isSub: true,
    isCertified: false,
    jobTitle: "Business Analyst",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "450",
    totalSpent: "9k",
  ),
  User(
    id: 8,
    name: "Olivia Martinez",
    email: "olivia@example.com",
    age: 31,
    isSub: false,
    isCertified: true,
    jobTitle: "HR Manager",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "550",
    totalSpent: "11k",
  ),
  User(
    id: 9,
    name: "William Davis",
    email: "william@example.com",
    age: 33,
    isSub: true,
    isCertified: true,
    jobTitle: "Operations Manager",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "700",
    totalSpent: "14k",
  ),
  User(
    id: 10,
    name: "Charlotte Thomas",
    email: "charlotte@example.com",
    age: 24,
    isSub: false,
    isCertified: false,
    jobTitle: "Graphic Designer",
    profilePictureUrl:
    "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQyrsm9OOijHoa55nD2b4lMqQL6WmHpzCHSbxksFxUa9yFhKPy_",
    monthlyCap: "250",
    totalSpent: "6k",
  ),
];
